// Re-export all public YAML utilities from the split modules.
// This file preserves the original import path for backwards compatibility.
export {
  normalizeYamlLegacyValues,
  fetchYamlContent,
  parseYaml,
  normalizeYamlWhitespace,
  modelToYaml,
  yamlQuote,
  formatValue,
  formatFieldLine,
  updateYamlField,
  updateYamlTopLevelField,
  updateYamlOptionalTopLevelField,
  updateYamlTopLevelStringArray,
  renameRef,
  renameDataFlowRef,
  renameComponentRef,
  renameAssetRef,
  renameBoundaryRef,
  renameThreatRef,
  renameControlRef,
  removeRefFromArrayFields,
  appendYamlItem,
  reorderYamlSection,
  removeYamlItem,
} from './yaml';
